name: Publish Beta

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.inputs.ref}}
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 10
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

  publish-npm:
    if: github.repository == 'Sunoo/homebridge-philips-air'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{github.event.inputs.ref}}
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: node .github/workflows/prerelease.js
      - run: npm --no-git-tag-version version prerelease --preid=beta
      - run: npm publish --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
