name: Stale

on:
  issues:
   types: [reopened]
  schedule:
   - cron: "*/60 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
    - uses: actions/stale@v3.0.15
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
        stale-issue-label: 'stale'
        days-before-stale: 28
        days-before-close: 7
        exempt-issue-labels: 'long running,help wanted,tested config'
        remove-stale-when-updated: true
